Entrega 5 e 6
Insper/open-dev pull request #787
Opened 2023-08-30 15:12 UTC by JorasOliveira

contem as skills referentes a entrega 5 e 6, engrega 5 pode ser vista pela url na skill referente, deve conter apenas os arquivos corretos com relacao a entrega 6

2023-09-04 11:02 UTC, igordsm requested changes

2023-09-04 11:02 UTC, igordsm commented on docs/lessons/cli-model.pot
> +# Translations template for PROJECT.
Não é necessário mandar esses arquivos.

2023-09-04 11:02 UTC, igordsm commented on docs/lessons/06-localization-translation/cli.py
Esse arquivo é da atividade e não deve ser removido.

2023-09-04 11:02 UTC, igordsm commented on students/jorascco-achievements
> -gAAAAABk5e3Kr0dppxhAKqeuKH48HyzTl7RTb8B-RDaHv0nwsjAIU3MaKJ_0p-c2EBhJYvuB_yftaeWMdaEWahIfAhsO82DUFTkDSif5Cn89dklPkLFEKB0O22dogBvHrW-wgE-MD418cWfX7kJYKINGNnE99c3FkSrT8H4NaIm1NJTG46FSN59LAoF0_HqaKFHUHME
A única modificação no seu PR deverá ser neste arquivo. Os outros não devem ser entregues.

2023-09-04 12:31 UTC, JorasOliveira commented on docs/lessons/06-localization-translation/cli.py
colocado de volta

2023-09-04 12:31 UTC, JorasOliveira commented on students/jorascco-achievements
> -gAAAAABk5e3Kr0dppxhAKqeuKH48HyzTl7RTb8B-RDaHv0nwsjAIU3MaKJ_0p-c2EBhJYvuB_yftaeWMdaEWahIfAhsO82DUFTkDSif5Cn89dklPkLFEKB0O22dogBvHrW-wgE-MD418cWfX7kJYKINGNnE99c3FkSrT8H4NaIm1NJTG46FSN59LAoF0_HqaKFHUHME
entendi

2023-09-04 12:32 UTC, JorasOliveira commented
adicionei a skill 4 ao PR para facilitar

2023-09-11 10:42 UTC, JorasOliveira commented
Oi, poderia dar uma olhada no PR?

2023-09-11 11:13 UTC, merged